name: Create release
on:
  release:
    types:
      - published

env:
  PHP_VERSION: '8.2'
  NODE_VERSION: '22'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Install JS dependencies
        run: npm ci

      - name: Build widget bundle
        run: npm run build:production

      - name: Zip plugin
        run: |
          zip -r ${{ github.event.repository.name }}.zip \
            gravityforms-altcha.php \
            build/ \
            src/ \
            composer.json \
            README.md \
            LICENSE

      - name: Attach asset to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}.zip

  update-satis:
    needs: build
    uses: generoi/packagist/.github/workflows/update.yml@master
    secrets:
      token: ${{ secrets.PACKAGIST_UPDATE_PAT }}
